# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor = torch.rand(7, 7)
print(tensor)


tensor([[0.6849, 0.7344, 0.5954, 0.3797, 0.6060, 0.5279, 0.6435],
        [0.6838, 0.5585, 0.2178, 0.7602, 0.5841, 0.4312, 0.1296],
        [0.5938, 0.4681, 0.0461, 0.1854, 0.9629, 0.1120, 0.3633],
        [0.0030, 0.7170, 0.7816, 0.0682, 0.4228, 0.7046, 0.8966],
        [0.3140, 0.8739, 0.5885, 0.1090, 0.8067, 0.0456, 0.0358],
        [0.9817, 0.5562, 0.6739, 0.9319, 0.2817, 0.0236, 0.2264],
        [0.0673, 0.8022, 0.1483, 0.1184, 0.5668, 0.3279, 0.0357]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
import torch
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
tensor2_T = tensor2.T
result = torch.matmul(tensor1, tensor2_T)
print(result)


tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
import torch
torch.manual_seed(0)
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
tensor2_T = tensor2.T
result = torch.matmul(tensor1, tensor2_T)
print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
import torch
torch.manual_seed(0)
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU random seed set to 1234 ")
else:
    print("GPU not available ")

GPU random seed set to 1234 



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
import torch
torch.manual_seed(1234)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
    tensor1 = torch.rand(2, 3).to(device)
    tensor2 = torch.rand(2, 3).to(device)


    print(tensor1, tensor2)
else:
    print("GPU not available")


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
import torch
torch.manual_seed(1234)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:\n", device)


    tensor1 = torch.rand(2, 3).to(device)
    tensor2 = torch.rand(2, 3).to(device)


    tensor2_T = tensor2.T


    result = torch.matmul(tensor1, tensor2_T)


    print(result, result.shape)
else:
    print("GPU not available")

Device:
 cuda
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
import torch
result = torch.tensor([[0.3647, 0.4709],
                       [0.5184, 0.5617]], device='cuda:0')

max_value = torch.max(result)
min_value = torch.min(result)


print("Maximum value:", max_value)
print("Minimum value:", min_value)



Maximum value: tensor(0.5617, device='cuda:0')
Minimum value: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)
print("Maximum index:", max_index)
print("Minimum index:", min_index)


Maximum index: tensor(3, device='cuda:0')
Minimum index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
import torch
torch.manual_seed(7)
tensor1 = torch.rand(1, 1, 1, 10)
tensor2 = torch.squeeze(tensor1)
print(tensor1, tensor1.shape)
print()
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
