# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch
tensor = torch.rand(7, 7)
print(tensor)


tensor([[0.0105, 0.3741, 0.4410, 0.6649, 0.4429, 0.6701, 0.2220],
        [0.9439, 0.1041, 0.3845, 0.4129, 0.3340, 0.6266, 0.3357],
        [0.8952, 0.2462, 0.3231, 0.8892, 0.6103, 0.4732, 0.7900],
        [0.5972, 0.3095, 0.4982, 0.6796, 0.4150, 0.6588, 0.5536],
        [0.1243, 0.3760, 0.0564, 0.3196, 0.4207, 0.2068, 0.2904],
        [0.9093, 0.1514, 0.1425, 0.6181, 0.6705, 0.9957, 0.4441],
        [0.6104, 0.7564, 0.5168, 0.8779, 0.1108, 0.4076, 0.1114]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
import torch
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
tensor2_T = tensor2.T
result = torch.matmul(tensor1, tensor2_T)
print(result)


tensor([[1.2083],
        [1.4254],
        [0.9658],
        [1.4481],
        [1.3276],
        [1.4248],
        [2.0698]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
import torch
torch.manual_seed(0)
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
tensor2_T = tensor2.T
result = torch.matmul(tensor1, tensor2_T)
print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
import torch
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
import torch
torch.manual_seed(1234)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:", device)
    tensor1 = torch.rand(2, 3).to(device)
    tensor2 = torch.rand(2, 3).to(device)


    print(tensor1, tensor2)
else:
    print("GPU not available")


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
import torch
torch.manual_seed(1234)
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Device:\n", device)


    tensor1 = torch.rand(2, 3).to(device)
    tensor2 = torch.rand(2, 3).to(device)


    tensor2_T = tensor2.T


    result = torch.matmul(tensor1, tensor2_T)


    print(result, result.shape)
else:
    print("GPU not available")

Device:
 cuda
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
import torch
result = torch.tensor([[0.3647, 0.4709],
                       [0.5184, 0.5617]], device='cuda:0')

max_value = torch.max(result)
min_value = torch.min(result)


print("Maximum value:", max_value)
print("Minimum value:", min_value)



Maximum value: tensor(0.5617, device='cuda:0')
Minimum value: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
max_index = torch.argmax(result)
min_index = torch.argmin(result)
print("Maximum index:", max_index)
print("Minimum index:", min_index)


Maximum index: tensor(3, device='cuda:0')
Minimum index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
import torch
torch.manual_seed(7)
tensor1 = torch.rand(1, 1, 1, 10)
tensor2 = torch.squeeze(tensor1)
print(tensor1, tensor1.shape)
print()
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
